// components/Frames/About.vue
<script setup lang="ts">
import { formatDate } from "~/utils";

const date = new Date("2022-04-21");
const dateFormated = formatDate(date);
</script>

<template>
  <div class="window-width mx-auto my-10 flex flex-col gap-5">
    <h2 id="about" class="text-emerald-500">Sobre</h2>

    <div class="flex flex-col gap-5 lg:flex-row">
      <article
        style="flex: 1"
        class="flex h-[336px] flex-col gap-3 overflow-auto text-justify"
      >
        <span>
          Me chamo Wesley Gomes de Araújo, sou graduado em Licenciatura em
          Matemática pela Universidade de Pernambuco. Iniciei meus estudos na
          área de programação em 2021 e atuo no mercado de desenvolvimento a
          mais de {{ dateFormated }}.
        </span>
        <span>
          Atualmente estudo e trabalho com Desenvolvimento Web, utilizando
          stacks como Node, React, Vue, Typescript e Go. Sempre me dedico em
          diversos projetos pessoais os quais compartilho em meu repositório no
          GitHub.
        </span>
        <span>
          Procuro contribuir o máximo para o crescimento e melhora da equipe e
          empresa que faço/farei parte, estou sempre disposto a aprender e me
          adaptar as diversas situações e desafios propostos, buscando evoluir
          como pessoa e profissional.
        </span>
      </article>

      <span style="flex: 1">
        <NuxtImg
          src="/about-image.jpg"
          alt="Wesley Araújo"
          class="rounded-md"
        />
      </span>
    </div>
  </div>
</template>

// src/Components/About/index.tsx
import Image from "next/image";
import matematicaImg from "../../Assets/Images/image-matematica.jpg";
import style from "./index.module.scss";

export default function About() {
  return (
    <>
      <div id="about"></div>
      <div className={style.about} data-aos="fade-up">
        <h2 className="subTitle">About</h2>
        <div className={style.aboutContainer}>
          <div className={style.descriptionAbout}>
            <p className="paragraph">
              Meu nome é Wesley Gomes de Araújo, sou graduado em Licenciatura em
              Matemática pela Universidade de Pernambuco. Atraído pela
              programação, iniciei no ano de 2021 os estudos nessa área,
              especificamente algumas linguagens como HTML, CSS e JavaScript.
            </p>
            <br />
            <p className="paragraph">
              Atualmente estou estudando sobre Desenvolvimento Web, me
              aprofundando em front-end para futuramente avançar no back-end e
              virar um programador FullStack. Venho me dedicando em diversos
              projetos pessoais os quais sempre compartilho em meu repositório
              no
              <a href="https://github.com/wesleyara">GitHub</a> .
            </p>
            <br />
            <p className="paragraph">
              Tenho como objetivo contribuir o máximo para a equipe e a empresa,
              estou sempre disposto a aprender mais e me adaptar as diversas
              situações as quais somos apresentados diariamente. Busco evoluir
              como profissional e crescer dentro da empresa.
            </p>
            <br />
            <p className="paragraph">
              Apaixonado por música, minha banda favorita é o Red Hot Chili
              Peppers, e como bom geek, gosto muito de RPG de mesa, séries,
              animes e HQ&apos;s. Enfim, isso é um pouco do que eu queria contar
              sobre mim.
            </p>
          </div>

          <div className={style.descriptionImage}>
            <Image
              className={style.imgAbout}
              width="500px"
              height={320}
              src={matematicaImg}
              alt=""
            />
          </div>
        </div>
      </div>
    </>
  );
}
