// app.vue
<script setup lang="ts">
useSeoMeta({
  title: "Portfólio - Wesley Araújo",
  description: "Portfólio do Desenvolvedor Wesley Araújo",
  ogTitle: "Portfólio - Wesley Araújo",
  ogDescription: "Portfólio do Desenvolvedor Wesley Araújo",
  ogImage: "https://wesleyaraujo.dev/favicon.png",
  ogImageUrl: "https://wesleyaraujo.dev/favicon.png",
});

useHead({
  htmlAttrs: {
    lang: "en",
  },
  link: [
    {
      rel: "icon",
      type: "image/svg",
      href: "/favicon.svg",
    },
  ],
});
</script>

<template>
  <NuxtPage />
</template>

<style lang="scss">
@use "~/assets/css/typography.scss";
@use "~/assets/css/globals.scss";
</style>

// src/pages/_app.tsx
import "../styles/index.scss";
import Head from "next/head";
import type { AppProps } from "next/app";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Wesley Araújo | Portfólio</title>
        <link rel="shortcut icon" href="../..//icon.png" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
