// src/components/About/index.tsx
import Image from "next/image";
import { useEffect, useState } from "react";

import matematicaImg from "../../assets/images/image-matematica.jpg";
import { formatDate } from "../../utils";
import { Container } from "./style";

const date = new Date("2022-04-21");

export default function About() {
  const [currentDate, setCurrentDate] = useState("0");

  useEffect(() => {
    const formattedDate = formatDate(date);
    setCurrentDate(formattedDate);
  }, []);

  return (
    <>
      <Container data-aos="fade-up">
        <h2 className="subTitle">Sobre</h2>
        <div className="aboutContainer">
          <div className="descriptionAbout">
            <p className="paragraph">
              Meu nome é Wesley Gomes de Araújo, sou graduado em Licenciatura em
              Matemática pela Universidade de Pernambuco. Dei início aos meus
              estudos na programação em Setembro de 2021 e já atuo no mercado de
              desenvolvimento a mais de {currentDate}.
            </p>
            <br />
            <p className="paragraph">
              Atualmente estou estudando e trabalhando com Desenvolvimento Web,
              utilizando stack como Node, React e Typescript. Sempre me
              dedicando em diversos projetos pessoais os quais compartilho em
              meu repositório no{" "}
              <a href="https://github.com/wesleyara">GitHub</a>.
            </p>
            <br />
            <p className="paragraph">
              Tenho como objetivo contribuir o máximo para a equipe e a empresa,
              estou sempre disposto a aprender mais e me adaptar as diversas
              situações as quais somos apresentados diariamente. Busco evoluir
              como profissional e crescer dentro da empresa.
            </p>
          </div>

          <div className="descriptionImage">
            <Image layout="responsive" src={matematicaImg} alt="" />
          </div>
        </div>
      </Container>
    </>
  );
}

// components/Frames/About.vue
<script setup lang="ts">
import { formatDate } from "~/utils";

const date = new Date("2022-04-21");
const dateFormated = formatDate(date);
</script>

<template>
  <div class="window-width mx-auto my-10 flex flex-col gap-5">
    <h2 id="about" class="text-emerald-500">Sobre</h2>

    <div class="flex flex-col gap-5 lg:flex-row">
      <article
        style="flex: 1"
        class="flex h-[336px] flex-col gap-3 overflow-auto text-justify"
      >
        <span>
          Me chamo Wesley Gomes de Araújo, sou graduado em Licenciatura em
          Matemática pela Universidade de Pernambuco. Iniciei meus estudos na
          área de programação em 2021 e atuo no mercado de desenvolvimento a
          mais de {{ dateFormated }}.
        </span>
        <span>
          Atualmente estudo e trabalho com Desenvolvimento Web, utilizando
          stacks como Node, React, Vue, Typescript e Go. Sempre me dedico em
          diversos projetos pessoais os quais compartilho em meu repositório no
          GitHub.
        </span>
        <span>
          Procuro contribuir o máximo para o crescimento e melhora da equipe e
          empresa que faço/farei parte, estou sempre disposto a aprender e me
          adaptar as diversas situações e desafios propostos, buscando evoluir
          como pessoa e profissional.
        </span>
      </article>

      <span style="flex: 1">
        <NuxtImg
          src="/about-image.jpg"
          alt="Wesley Araújo"
          class="rounded-md"
        />
      </span>
    </div>
  </div>
</template>
